
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.34.31937.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/3.26.4/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "message-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.34.31937.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        注意: 包含文件:  D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "注意: 包含文件:  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ad4owh"
      binary: "D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ad4owh"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-ad4owh
        
        Run Build Command(s):C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_7cdaa\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_7cdaa.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_7cdaa.dir\\build
        Building C object CMakeFiles/cmTC_7cdaa.dir/CMakeCCompilerABI.c.obj
        	"C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_7cdaa.dir\\CMakeCCompilerABI.c.obj.d --working-dir=D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ad4owh --filter-prefix="注意: 包含文件:  " -- C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\59822\\AppData\\Local\\Temp\\nm297D.tmp
        CMakeCCompilerABI.c
        ?鈷? 鍖呭惈鏂囦欢:  C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.26\\Modules\\CMakeCompilerABI.h
        Linking C executable cmTC_7cdaa.exe
        	"C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_7cdaa.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_7cdaa.dir\\objects1.rsp @C:\\Users\\59822\\AppData\\Local\\Temp\\nm2A3A.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_7cdaa.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_7cdaa.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_7cdaa.dir/manifest.res CMakeFiles\\cmTC_7cdaa.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_7cdaa.dir\\objects1.rsp /out:cmTC_7cdaa.exe /implib:cmTC_7cdaa.lib /pdb:D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ad4owh\\cmTC_7cdaa.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_7cdaa.dir/intermediate.manifest CMakeFiles\\cmTC_7cdaa.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_7cdaa.dir/intermediate.manifest /out:CMakeFiles\\cmTC_7cdaa.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_7cdaa.dir/manifest.res CMakeFiles\\cmTC_7cdaa.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_7cdaa.dir\\objects1.rsp /out:cmTC_7cdaa.exe /implib:cmTC_7cdaa.lib /pdb:D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-ad4owh\\cmTC_7cdaa.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_7cdaa.dir/intermediate.manifest CMakeFiles\\cmTC_7cdaa.dir/manifest.res
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-oct5hs"
      binary: "D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-oct5hs"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/myProjectCpp/clion_proj/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-oct5hs
        
        Run Build Command(s):C:/CLino/CLion 2023.2.2/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_a871c\\fast && 	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\nmake.exe"  -f CMakeFiles\\cmTC_a871c.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_a871c.dir\\build
        Building CXX object CMakeFiles/cmTC_a871c.dir/CMakeCXXCompilerABI.cpp.obj
        	"C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_a871c.dir\\CMakeCXXCompilerABI.cpp.obj.d --working-dir=D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-oct5hs --filter-prefix="注意: 包含文件:  " -- C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\cl.exe @C:\\Users\\59822\\AppData\\Local\\Temp\\nm2DD3.tmp
        CMakeCXXCompilerABI.cpp
        ?鈷? 鍖呭惈鏂囦欢:  C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.26\\Modules\\CMakeCompilerABI.h
        Linking CXX executable cmTC_a871c.exe
        	"C:\\CLino\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_a871c.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\mt.exe --manifests -- C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a871c.dir\\objects1.rsp @C:\\Users\\59822\\AppData\\Local\\Temp\\nm2EAE.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_a871c.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_a871c.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_a871c.dir/manifest.res CMakeFiles\\cmTC_a871c.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a871c.dir\\objects1.rsp /out:cmTC_a871c.exe /implib:cmTC_a871c.lib /pdb:D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-oct5hs\\cmTC_a871c.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a871c.dir/intermediate.manifest CMakeFiles\\cmTC_a871c.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\mt.exe /nologo /manifest CMakeFiles\\cmTC_a871c.dir/intermediate.manifest /out:CMakeFiles\\cmTC_a871c.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100220~1.0\\x64\\rc.exe /fo CMakeFiles\\cmTC_a871c.dir/manifest.res CMakeFiles\\cmTC_a871c.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\MICROS~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1434~1.319\\bin\\Hostx64\\x64\\link.exe /nologo @CMakeFiles\\cmTC_a871c.dir\\objects1.rsp /out:cmTC_a871c.exe /implib:cmTC_a871c.lib /pdb:D:\\myProjectCpp\\clion_proj\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-oct5hs\\cmTC_a871c.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_a871c.dir/intermediate.manifest CMakeFiles\\cmTC_a871c.dir/manifest.res
        
      exitCode: 0
...
